services:
  mongodb:
    ports:
    - 27017:27017
    image: mongo:5.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb: